### PR TITLE
WIFEXITED returns true if program exits normally

### PR DESCRIPTION
**Pull request by tsmish**

### CODE REVIEW

**Comment by xelez** [comment]
And what if program exits normally and returns non-zero exit status? Should it be _OK or _RE? Ejudge, as I know, also treats this situation as _RE, although I'm not sure that's right.

**Comment by tsmish** [comment]
```c++
#include <cstdio>

int main() {
	printf("%d", 1/0);
}
```
exit code: 13

**Comment by tsmish** [comment]
```c
#include <stdio.h>

int main() {
	printf("Hello, world!");
}
```
exit code: 13

**Comment by tsmish** [comment]
It matters when we are talking about interpreted languages, like python.
For example:

``` python
print(1/0)
```

returns exit code 1, but not crashes.
Also it may be nice way to debug your program without using assert.

But basic "Hello, world" program compiled with gcc returns 13, printf return code.

``` c
#include <stdio.h>

int main() {
    printf("Hello, world!");
}
```

Although it fixes with compiler flag.
Seems that problem happens only in programs compiled by gcc with standard flags.

**Comment by xelez** [comment]
You forgot `return 0;` in the last example. It's an error, you must return 0 to indicate that program finished successfully.

**Pull request closed without merging**
